app/__init__.py
from flask import Flask
from flask_socketio import SocketIO
from dotenv import load_dotenv
import os
import mysql.connector

load_dotenv()

app = Flask(__name__)
app.secret_key = os.getenv("SECRET_KEY")

db_config = {
    "host": os.getenv("DB_HOST"),
    "user": os.getenv("DB_USER"),
    "password": os.getenv("DB_PASSWORD"),
    "database": os.getenv("DB_NAME")
}

socketio = SocketIO(app)


def get_db_connection():
    connection = mysql.connector.connect(**db_config)
    return connection


from app.routes import main
app.register_blueprint(main)

app/routes.py
from flask import Blueprint, request, redirect, url_for, session, flash, render_template
from flask_socketio import disconnect
from confluent_kafka import Producer, Consumer
from werkzeug.security import generate_password_hash, check_password_hash
from functools import wraps
import mysql.connector
import json
from app import get_db_connection, socketio

main = Blueprint("main", __name__)

# track active users
active_users = []

producer = Producer({"bootstrap.servers": "localhost:9092"})


def message_to_kafka(message_data):
    try:
        message_to_bytes = json.dumps(message_data).encode("utf-8")
        producer.produce("chat-messages", value=message_to_bytes)
        producer.flush()
    except Exception as e:
        print(f"Error producing message: {str(e)}")


def user_auth(f):
    @wraps(f)
    def check_username(*args, **kwargs):
        if "username" not in session:
            flash("Please log in to access this page.", "danger")
            return redirect(url_for("main.index"))
        return f(*args, **kwargs)
    return check_username


@main.route("/")
def index():
    if "username" in session:
        return redirect(url_for("main.chat"))
    return render_template("login.html")


@main.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        connection = None
        cursor = None

        try:
            connection = get_db_connection()
            cursor = connection.cursor(dictionary=True)
            cursor.execute("SELECT * FROM users WHERE username = %s", (username,))
            user = cursor.fetchone()

            if user and check_password_hash(user["password"], password):
                session["username"] = username
                return redirect(url_for("main.chat"))
            else:
                flash("Invalid username or password. Please try again.", "danger")
                return redirect(url_for("main.login"))

        except mysql.connector.Error as db_error:
            flash(f"Database error occurred. {str(db_error)}", "danger")
            return redirect(url_for("main.login"))

        except Exception as e:
            flash(f"An error occurred: {str(e)}", "danger")
            return redirect(url_for("main.login"))

        finally:
            if cursor is not None:
                cursor.close()
            if connection is not None:
                connection.close()

    return render_template("login.html")


@main.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        connection = None
        cursor = None

        try:
            connection = get_db_connection()
            cursor = connection.cursor()
            cursor.execute("SELECT * FROM users WHERE username=%s", (username,))
            user_exist = cursor.fetchone()

            if user_exist:
                flash("Username already exists, please choose a different one.", "danger")
                return redirect(url_for("main.signup"))

            hashed_password = generate_password_hash(password)
            cursor.execute("INSERT INTO users (username, password) VALUES (%s, %s)", (username, hashed_password))
            connection.commit()

            flash("Sign up successful! You can now log in.", "success")
            return redirect(url_for("main.login"))

        except mysql.connector.Error as db_error:
            flash(f"Database error occurred. {str(db_error)}", "danger")
            return redirect(url_for("main.signup"))

        except Exception as e:
            flash(f"An error occurred: {str(e)}", "danger")
            return redirect(url_for("main.signup"))

        finally:
            if cursor is not None:
                cursor.close()
            if connection is not None:
                connection.close()

    return render_template("signup.html")


@main.route("/logout")
def logout():
    session.clear()
    flash("You have been logged out.", "success")
    return redirect(url_for("main.index"))


@main.route("/chat")
@user_auth
def chat():
    if "username" not in session:
        flash("You must be logged in to access the chat.", "danger")
        return redirect(url_for("main.index"))

    previous_messages = consume_message_history()

    return render_template("chat.html", username=session["username"], previous_messages=previous_messages)


@socketio.on("connect")
def handle_connect():
    if "username" not in session:
        disconnect()
    else:
        username = session["username"]
        if username not in active_users:
            active_users.append(username)
        print(f"{username} connected. Active users: {active_users}")

        message_history = consume_message_history()

        for message in message_history:
            socketio.emit("receive_message", message, to=request.sid)

        socketio.emit("active_users", active_users)


@socketio.on("send_message")
def handle_send_message(data):
    message = data["message"]
    username = session.get("username")

    message_data = {
        "username": username,
        "message": message
    }

    # sending message to kafka
    message_to_kafka(message_data)

    socketio.emit("receive_message", message_data)


@socketio.on("disconnect")
def handle_disconnect():
    if "username" in session:
        username = session["username"]
        if username in active_users:
            active_users.remove(username)
            print(f"{username} disconnected. Active user: {active_users}")
        socketio.emit("active_users", active_users)


def consume_message_history():
    consumer = get_kafka_consumer()

    previous_messages = []

    while True:
        message = consumer.poll(1.0)
        if message is None:
            break
        if message.error():
            print(f"Error retrieving messages: {message.error()}")
            continue
        message_value = json.loads(message.value().decode("utf-8"))
        previous_messages.append(message_value)

    consumer.close()
    return previous_messages


def get_kafka_consumer():
    consumer = Consumer({
        'bootstrap.servers': 'localhost:9092',
        'group.id': 'chat-consumer-group',
        'auto.offset.reset': 'earliest',
        "enable.auto.commit": True
    })
    consumer.subscribe(["chat-messages"])
    return consumer

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Chat App</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Chat</a>
        <ul class="nav">
          {% if session.get('username') %}
          <li class="nav-item">
            <a
              href="{{ url_for('main.logout') }}"
              class="nav-link active"
              aria-current="page"
              >Logout</a
            >
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.signup') }}">Sign Up</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %}
      <div class="row justify-content-center">
        <div class="col-md-6">
          <ul class="flashes mt-3">
            {% for category, message in messages %}
            <li
              class="alert alert-{{ category }}"
              role="alert"
              style="list-style-type: none"
            >
              {{ message }}
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
      {% endif %} {% endwith %} {% block content %}{% endblock %}
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
      integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/chat.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Chat App</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Chat</a>
        <ul class="nav">
          {% if session.get('username') %}
          <li class="nav-item">
            <a
              href="{{ url_for('main.logout') }}"
              class="nav-link active"
              aria-current="page"
              >Logout</a
            >
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.signup') }}">Signup</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container mt-5">
      <div class="row">
        <!-- chat messages section -->
        <div class="col-md-8">
          <h4>Welcome, {{ username }}!</h4>
          <div
            id="messages"
            class="border p-3"
            style="height: 400px; overflow-y: scroll"
          >
            <!-- render persisted messages from kafka -->
            {% for message in previous_messages %}
            <div>
              <strong>{{ message.username }}: </strong
              ><span>{{message.message}}</span>
            </div>
            {% endfor %}
          </div>
          <form id="message-form">
            <div class="input-group mt-3">
              <input
                type="text"
                id="message-input"
                class="form-control"
                placeholder="Enter your message..."
                style="
                  border-top-right-radius: 7px;
                  border-bottom-right-radius: 7px;
                "
              />
              <div class="input-group-append ms-3">
                <button class="btn btn-primary" type="submit">Send</button>
              </div>
            </div>
          </form>
        </div>

        <!-- active users section -->
        <div class="col-md-4 mt-2">
          <h5>Active Users</h5>
          <ul id="active-users" class="list-group">
            <!-- active users listed here -->
          </ul>
        </div>
      </div>
    </div>

    <script>
      $(document).ready(function () {
        let socket = io.connect(window.location.origin);

        // listening for new messages
        socket.on("receive_message", function (data) {
          let message =
            "<div><strong>" +
            data.username +
            ":</strong> " +
            data.message +
            "</div>";
          $("#messages").append(message);
          $("#messages").scrollTop($("#messages")[0].scrollHeight);
        });

        // listening for active users list updates
        socket.on("active_users", function (users) {
          $("#active-users").empty();
          users.forEach(function (user) {
            $("#active-users").append(
              '<li class="list-group-item">' + user + "</li>"
            );
          });
        });

        // send new message
        $("#message-form").submit(function (event) {
          event.preventDefault();
          var message = $("#message-input").val();
          if (message.trim() !== "") {
            socket.emit("send_message", { message: message });
            $("#message-input").val("");
          }
        });
      });
    </script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
      integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/login.html
{% extends "base.html" %} {% block content %}
<div class="row justify-content-center mt-5">
  <div class="col-md-6">
    <div class="card">
      <div class="card-body">
        <h2 class="text-center">Login</h2>
        <form method="POST" action="{{ url_for('main.login') }}">
          <div class="form-group">
            <label for="username">Username</label>
            <input
              type="text"
              class="form-control"
              name="username"
              id="username"
              required
            />
          </div>
          <div class="form-group mt-3">
            <label for="password">Password</label>
            <input
              type="password"
              class="form-control"
              name="password"
              id="password"
              required
            />
          </div>
          <button type="submit" class="btn btn-success mt-3 fw-bold">
            Login
          </button>
          <p class="mt-3 text-center text-muted" style="font-size: small">
            New user?
            <a
              class="link"
              style="text-decoration: none"
              href="{{ url_for('main.signup') }}"
              >Sign Up</a
            >
            here
          </p>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %} {% block content %}
<div class="row justify-content-center mt-5">
  <div class="col-md-6">
    <div class="card">
      <div class="card-body">
        <h2 class="text-center">Sign Up</h2>
        <form method="POST" action="{{ url_for('main.signup') }}">
          <div class="form-group">
            <label for="username">Username</label>
            <input
              type="text"
              class="form-control"
              name="username"
              id="username"
              required
            />
          </div>
          <div class="form-group mt-3">
            <label for="password">Password</label>
            <input
              type="password"
              class="form-control"
              name="password"
              id="password"
              required
            />
          </div>
          <button type="submit" class="btn btn-success mt-3 fw-bold">
            Sign Up
          </button>
          <p class="mt-3 text-center text-muted" style="font-size: small">
            Already have an account?
            <a
              class="link"
              style="text-decoration: none"
              href="{{ url_for('main.login') }}"
              >Login</a
            >
            here
          </p>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}